### ISSUE TITLE
Platform code exception

### ISSUE THREAD

**Issue by vpsq** [krista-koivisto/isolate_handler#24]
Good day!   Could you help? 

Your documentation says 

> Besides, it allows the isolates to call platform plugins, overcoming a limitation of the original ones

But I am experiencing a PlatformException

More info:

Target API: 29
Dart SDK: 2.13.4
Flutter: 2.2.3

pubspec.yaml: 
```yaml
isolate_handler: 1.0.0
photo_manager: ^1.3.1
```

```java 
Exception has occurred.
PlatformException (PlatformException(error, Activity for the permission request is not exist., null, java.lang.NullPointerException: Activity for the permission request is not exist.
	at top.kikt.imagescanner.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:116)
	at top.kikt.imagescanner.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:102)
	at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:221)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
))
```

Using the PhotoManager plugin in your modified example:

```dart
iimport 'package:flutter/material.dart';

/// Welcome to the Isolate Handler example
///
/// In this example we will take a look at how to spawn an isolate and allow it
/// to communicate with the main isolate. The isolate will be using a plugin, too.
///
/// This will be a simple, but complete project. We will start an isolate and
/// send it a string, have it add a path to it and return the value.
///
/// We will also give our isolate a name to make it easy to access from
/// anywhere.

import 'package:isolate_handler/isolate_handler.dart';
// import 'package:path_provider/path_provider.dart';
import 'package:photo_manager/photo_manager.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
// Let's create a new IsolateHandler instance. This is what we will use
// to spawn isolates.
  final isolates = IsolateHandler();

// Variable where we can store the message.
  String isolateMessage = '';

  @override
  void initState() {
    super.initState();

    isolates.spawn<String>(entryPoint,
        name: 'isolate',
        onReceive: communicationFromIsolate,
        onInitialized: () => isolates.send("test", to: "isolate"));
  }

  void communicationFromIsolate(dynamic data) {
    // Show the new message.
    setState(() {
      isolateMessage = data.toString();
    });

    // We will no longer be needing the isolate, let's dispose of it.
    isolates.kill('isolate');
  }

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            title: const Text('Isolate Handler example'),
          ),
          body: Center(child: Text(isolateMessage)),
        ),
      );
}

// This function happens in the isolate.
void entryPoint(Map<String, dynamic> context) async {
  final messenger = HandledIsolate.initialize(context);

  messenger.listen((msg) async {
    // Use a plugin to get some new value to send back to the main isolate.
    List<AssetPathEntity> _deviceAlbumList =
        await PhotoManager.getAssetPathList(onlyAll: true);
    messenger.send(_deviceAlbumList.length);
  });
}

```

Thanks!

**Comment by vpsq** [comment]
On further inspection, it seems like an issue with the PhotoManager plugin.  I have filed an issue with the PhotoManager plugin devs. 

Open to any suggestions or ideas, therefore not closing the issue here.

**Comment by deakjahn** [comment]
Yep, simply the native part had an exception.
